const cfg=window.DIDDY_CONFIG||{};const sb=cfg.SUPABASE_URL&&cfg.SUPABASE_ANON_KEY?supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY):null;
let S={levels:[],players:[],records:[],points:[],settings:null,recordCount:0,recordPage:0};
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function msg(t,good=true){$('auth').innerHTML=`<div class="panel ${good?'success':'error'}">${t}</div>`}
function pointsFor(level){return Number(S.points[Math.max(0,Number(level?.rank||1)-1)]||0)}
async function load(){
 const q=await Promise.all([
  sb.from('list_settings').select('*').limit(1).single(),
  sb.from('levels').select('*').order('section').order('rank'),
  sb.from('player_leaderboard').select('*').order('total_points',{ascending:false}),
  sb.from('point_values').select('*').order('rank'),
  sb.from('featured_level').select('*').limit(1)
 ]);
 const err=q.find(x=>x.error);if(err?.error){msg(`Database error: ${esc(err.error.message)}`,false);return}
 const {count,error:ce}=await sb.from('records').select('id',{count:'exact',head:true});if(ce){msg(`Database error: ${esc(ce.message)}`,false);return}
 S={settings:q[0].data,levels:q[1].data||[],players:q[2].data||[],records:[],points:(q[3].data||[]).map(x=>x.points),featured:q[4].data?.[0],recordCount:count||0,recordPage:0};
 render();await loadRecords(0);
}
function render(){
 $('adminApp').hidden=false;$('list_name').value=S.settings?.list_name||'';$('tagline').value=S.settings?.tagline||'';
 const pointsInPlay=S.players.reduce((n,p)=>n+Number(p.total_points||0),0);
 if($('aqLevels')){$('aqLevels').textContent=S.levels.length;$('aqPlayers').textContent=S.players.length;$('aqVictories').textContent=S.recordCount;$('aqPoints').textContent=pointsInPlay.toLocaleString()}
 $('pointsGrid').innerHTML=S.points.map((p,i)=>`<label class="pointInput"><span>#${i+1}</span><input data-rank="${i+1}" type="number" min="0" value="${p}"></label>`).join('');
 renderLevels();
 $('recordPlayer').innerHTML=S.players.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('');
 $('recordLevel').innerHTML=S.levels.map(l=>`<option value="${l.id}">#${l.rank} · ${esc(l.name)} — ${pointsFor(l)} pts</option>`).join('');updateRecordPoints();
 $('playerAdmin').innerHTML=S.players.map(p=>`<div class="adminRow row between"><span><strong>${esc(p.name)}</strong><span class="meta">${p.victors||0} victories · ${Number(p.total_points||0).toLocaleString()} pts</span></span><button class="danger" onclick="deletePlayer('${p.id}')">Delete</button></div>`).join('')||'<div class="meta">No players yet.</div>';
 $('recordSearchPlayer').innerHTML='<option value="">All players</option>'+S.players.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('');$('recordSearchLevel').innerHTML='<option value="">All levels</option>'+S.levels.map(l=>`<option value="${l.id}">#${l.rank} · ${esc(l.name)}</option>`).join('');
 $('featuredSelect').innerHTML='<option value="">None</option>'+S.levels.map(l=>`<option value="${l.id}" ${(S.featured?.level_id===l.id||S.featured?.id===l.id)?'selected':''}>#${l.rank} · ${esc(l.name)}</option>`).join('');
 renderHallLinks();
}
function renderLevels(){const f=($('levelFilter').value||'').toLowerCase(),sec=$('adminSection').value;const a=S.levels.filter(l=>(sec==='all'||l.section===sec)&&[l.name,l.creator,l.verifier,l.holder,l.difficulty,l.status,l.aliases,l.notes].join(' ').toLowerCase().includes(f));$('levelEditor').innerHTML=a.map(l=>`<article class="adminRow bulkLevelRow"><div class="row between"><strong><label class="bulkCheck"><input type="checkbox" class="bulkLevel" value="${l.id}" onchange="updateBulkCount()"><span>#${l.rank} · ${esc(l.name)}</span></label></strong><div class="row"><button class="secondary" onclick="editLevel('${l.id}')">Edit</button><button class="danger" onclick="deleteLevel('${l.id}')">Delete</button></div></div><div class="meta">${esc(l.section)} · ${esc(l.creator||'')} · ${esc(l.verifier||'')} · ${esc(l.holder||'')} · ${pointsFor(l)} pts</div></article>`).join('')||'<div class="panel">No matching levels.</div>'}
async function loadRecords(page=0){if(!sb)return;const pageSize=10;const from=page*pageSize,to=from+pageSize-1;const player=($('recordSearchPlayer')?.value||'').trim();const level=($('recordSearchLevel')?.value||'').trim();let q=sb.from('records').select('*,players(name),levels(rank,name)',{count:'exact'}).order('created_at',{ascending:false}).range(from,to);if(player)q=q.eq('player_id',player);if(level)q=q.eq('level_id',level);const {data,error,count}=await q;if(error){$('recordAdmin').innerHTML=`<div class="panel error">${esc(error.message)}</div>`;return}S.records=data||[];S.recordCount=count??S.recordCount;S.recordPage=page;$('aqVictories').textContent=S.recordCount;$('recordAdmin').innerHTML=S.records.map(r=>`<div class="adminRow row between"><span><strong>${esc(r.players?.name||'')}</strong> → #${r.levels?.rank||'?'} ${esc(r.levels?.name||'')} <span class="meta">· ${pointsFor({rank:r.levels?.rank})} pts · ${r.video_url?'video':'no video'} · ${new Date(r.created_at).toLocaleString()}</span></span><button class="danger" onclick="deleteRecord('${r.id}')">Remove</button></div>`).join('')||'<div class="meta">No victories match these filters.</div>';$('recordPager').innerHTML=`<button class="secondary" ${page===0?'disabled':''} onclick="loadRecords(${page-1})">← Previous</button><span class="meta">Page ${page+1} · ${count||0} total</span><button class="secondary" ${(from+pageSize>=(count||0))?'disabled':''} onclick="loadRecords(${page+1})">Next →</button>`}
function renderHallLinks(){if(!$('hallPlayer'))return;$('hallPlayer').innerHTML='<option value="">None</option>'+S.players.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('');$('hallLevel').innerHTML='<option value="">None</option>'+S.levels.map(l=>`<option value="${l.id}">#${l.rank} · ${esc(l.name)}</option>`).join('')}
function openLevelForm(level=null){$('levelModalTitle').textContent=level?'Edit level':'Add new level';$('levelId').value=level?.id||'';$('levelName').value=level?.name||'';$('levelSection').value=level?.section||'main';$('levelRank').value=level?.rank||'';$('levelCreator').value=level?.creator||'';$('levelVerifier').value=level?.verifier||'';$('levelHolder').value=level?.holder||'';$('levelDescription').value=level?.description||'';$('levelVideo').value=level?.video_url||'';$('levelThumbnail').value=level?.thumbnail_url||'';$('levelDifficulty').value=level?.difficulty||'';$('levelStatus').value=level?.status||'';$('levelAliases').value=level?.aliases||'';$('levelNotes').value=level?.notes||'';$('levelModal').hidden=false}
function closeLevelForm(){$('levelModal').hidden=true}
async function saveLevel(e){e.preventDefault();const id=$('levelId').value,name=$('levelName').value.trim(),section=$('levelSection').value,rank=Number($('levelRank').value),verifier=$('levelVerifier').value.trim();if(!name||!rank||rank<1)return alert('Enter a level name and valid rank.');if(!verifier)return alert('Verifier is required.');const p={p_section:section,p_rank:rank,p_name:name,p_creator:$('levelCreator').value.trim(),p_verifier:verifier,p_holder:$('levelHolder').value.trim(),p_description:$('levelDescription').value.trim(),p_video_url:$('levelVideo').value.trim(),p_thumbnail_url:$('levelThumbnail').value.trim()};const call=id?sb.rpc('move_level',{p_level_id:id,p_new_section:section,p_new_rank:rank,p_name:name,p_creator:p.p_creator,p_verifier:p.p_verifier,p_holder:p.p_holder,p_description:p.p_description,p_video_url:p.p_video_url,p_thumbnail_url:p.p_thumbnail_url}):sb.rpc('create_level',p);const {error}=await call;if(error)return alert(error.message);if(id){const {error:e2}=await sb.from('levels').update({difficulty:$('levelDifficulty').value.trim()||null,status:$('levelStatus').value.trim()||null,aliases:$('levelAliases').value.trim()||null,notes:$('levelNotes').value.trim()||null}).eq('id',id);if(e2)return alert(e2.message)}closeLevelForm();await load()}
function editLevel(id){const l=S.levels.find(x=>x.id===id);if(l)openLevelForm(l)}
function newLevel(){const sec=$('adminSection').value==='all'?'main':$('adminSection').value;const next=sec==='main'?S.levels.filter(l=>l.section==='main').length+1:sec==='extended'?46:101;openLevelForm({section:sec,rank:next})}
async function deleteLevel(id){if(!confirm('Delete this level? Its victories and history will also be removed.'))return;const {error}=await sb.from('levels').delete().eq('id',id);if(error)alert(error.message);else await load()}
async function deletePlayer(id){if(!confirm('Delete player and their victories?'))return;const {error}=await sb.from('players').delete().eq('id',id);if(error)alert(error.message);else await load()}
async function deleteRecord(id){if(!confirm('Remove this victory?'))return;const {error}=await sb.from('records').delete().eq('id',id);if(error)alert(error.message);else await loadRecords(S.recordPage)}
function updateRecordPoints(){const l=S.levels.find(x=>x.id===$('recordLevel').value);$('recordPoints').textContent=`Awards ${pointsFor(l)} points`;}
function selectedLevels(){return [...document.querySelectorAll('.bulkLevel:checked')].map(x=>x.value)}
function updateBulkCount(){$('bulkCount').textContent=`${selectedLevels().length} selected`}
$('settingsForm').onsubmit=async e=>{e.preventDefault();const {error}=await sb.from('list_settings').update({list_name:$('list_name').value,tagline:$('tagline').value}).eq('id',S.settings.id);if(error)alert(error.message);else await load()};
$('pointsForm').onsubmit=async e=>{e.preventDefault();for(const inp of [...document.querySelectorAll('#pointsGrid input')]){const {error}=await sb.from('point_values').update({points:Number(inp.value)}).eq('rank',Number(inp.dataset.rank));if(error)return alert(error.message)}await load()};
$('playerForm').onsubmit=async e=>{e.preventDefault();const {error}=await sb.from('players').insert({name:$('playerName').value.trim()});if(error)alert(error.message);else{$('playerName').value='';await load()}};
$('recordForm').onsubmit=async e=>{e.preventDefault();const payload={p_player_id:$('recordPlayer').value,p_level_id:$('recordLevel').value,p_progress:100,p_video_url:$('recordVideo').value.trim()||null};let {error}=await sb.rpc('add_victory',payload);if(error){alert(error.message);return}const id=undefined;const extra={};if($('recordAttempts').value)extra.attempts=Number($('recordAttempts').value);if($('recordSeconds').value)extra.completion_seconds=Number($('recordSeconds').value);if(Object.keys(extra).length){const {data}=await sb.from('records').select('id').eq('player_id',payload.p_player_id).eq('level_id',payload.p_level_id).maybeSingle();if(data?.id)await sb.from('records').update(extra).eq('id',data.id)}$('recordVideo').value='';$('recordAttempts').value='';$('recordSeconds').value='';await load()};
$('recordLevel').onchange=updateRecordPoints;$('levelFilter').oninput=renderLevels;$('adminSection').onchange=renderLevels;$('newLevelBtn').onclick=newLevel;$('levelClose').onclick=closeLevelForm;$('levelCancel').onclick=closeLevelForm;$('levelForm').onsubmit=saveLevel;$('featuredSave').onclick=async()=>{const level_id=$('featuredSelect').value||null;if(!level_id)return alert('Select a level first.');const {error}=await sb.rpc('set_featured_level',{p_level_id:level_id});if(error){alert(error.message);return}msg('Featured level saved.');await load()};
$('bulkApply').onclick=async()=>{const ids=selectedLevels();if(!ids.length)return alert('Select at least one level.');if(!confirm(`Apply changes to ${ids.length} levels?`))return;const diff=$('bulkDifficulty').value.trim()||null,status=$('bulkStatus').value.trim()||null,section=$('bulkSection').value;let {error}=await sb.from('levels').update({difficulty:diff,status}).in('id',ids);if(error){alert(error.message);return}if(section){for(const id of ids){const l=S.levels.find(x=>x.id===id);if(!l)continue;const targetRank=section===l.section?l.rank:(section==='main'?Math.min(l.rank,45):section==='extended'?Math.max(46,l.rank):Math.max(101,l.rank));const {error:e}=await sb.rpc('move_level',{p_level_id:id,p_new_section:section,p_new_rank:targetRank,p_name:l.name,p_creator:l.creator||'',p_verifier:l.verifier||'',p_holder:l.holder||'',p_description:l.description||'',p_video_url:l.video_url||null,p_thumbnail_url:l.thumbnail_url||null});if(e){alert(e.message);break}}}await load()};
$('bulkDelete').onclick=async()=>{const ids=selectedLevels();if(!ids.length)return alert('Select at least one level.');if(!confirm(`NUCLEAR DELETE ${ids.length} levels? This also removes their victories.`))return;const {error}=await sb.from('levels').delete().in('id',ids);if(error)alert(error.message);else await load()};
$('hallForm').onsubmit=async e=>{e.preventDefault();const {error}=await sb.from('hall_entries').insert({category:$('hallCategory').value.trim(),title:$('hallTitle').value.trim(),body:$('hallBody').value.trim(),year:Number($('hallYear').value)||null,player_id:$('hallPlayer').value||null,level_id:$('hallLevel').value||null});if(error)alert(error.message);else{e.target.reset();await loadHallAdmin()}};
async function loadHallAdmin(){const {data,error}=await sb.from('hall_entries').select('*').order('created_at',{ascending:false});if(error)return;$('hallAdminList').innerHTML=(data||[]).map(x=>`<div class="adminRow row between"><span><b>${esc(x.title)}</b><span class="meta"> · ${esc(x.category)}</span></span><button class="danger" onclick="deleteHall('${x.id}')">Delete</button></div>`).join('')||'<p class="meta">No exhibits yet.</p>'}async function deleteHall(id){if(!confirm('Delete this Hall exhibit?'))return;const {error}=await sb.from('hall_entries').delete().eq('id',id);if(error)alert(error.message);else loadHallAdmin()}
$('recordSearchPlayer').onchange=()=>loadRecords(0);$('recordSearchLevel').onchange=()=>loadRecords(0);$('recordSearchClear').onclick=()=>{$('recordSearchPlayer').value='';$('recordSearchLevel').value='';loadRecords(0)};
async function authGate(){const {data:{user}}=await sb.auth.getUser();if(!user){$('adminApp').hidden=true;$('auth').innerHTML='<section class="panel"><h2>🔐 Admin login</h2><form id="loginForm" class="formgrid"><label>Email<input id="loginEmail" type="email" required></label><label>Password<input id="loginPassword" type="password" required></label><button class="primary">Sign in</button></form></section>';document.getElementById('loginForm').onsubmit=async e=>{e.preventDefault();const {error}=await sb.auth.signInWithPassword({email:document.getElementById('loginEmail').value,password:document.getElementById('loginPassword').value});if(error)alert(error.message);else location.reload()};return false}const {data:isAdmin,error:adminErr}=await sb.rpc('is_admin');if(adminErr){msg('Admin check failed: '+esc(adminErr.message),false);return false}if(!isAdmin){msg('Signed in, but this account is not an admin.',false);return false}let role='admin';const {data:me}=await sb.from('admins').select('role').eq('user_id',user.id).maybeSingle();if(me?.role)role=me.role;$('auth').innerHTML='<div class="panel success row between"><span>Signed in as admin · '+esc(user.email||'')+' · '+esc(role)+'</span><button class="secondary" onclick="sb.auth.signOut().then(()=>location.reload())">Sign out</button></div>';return true}
async function start(){if(!sb){msg('Configure Supabase first.',false);return}if(!(await authGate()))return;await load();await loadHallAdmin();}
start();
