const cfg=window.DIDDY_CONFIG||{};
const sb=cfg.SUPABASE_URL&&cfg.SUPABASE_ANON_KEY?supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY):null;
let S={levels:[],players:[],records:[],points:[],settings:null};
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;');
function msg(t,good=true){$('auth').innerHTML=`<div class="panel ${good?'success':'error'}">${t}</div>`}
async function load(){const q=await Promise.all([sb.from('list_settings').select('*').limit(1).single(),sb.from('levels').select('*').order('section').order('rank'),sb.from('players').select('*').order('name'),sb.from('records').select('*,players(name)'),sb.from('point_values').select('*').order('rank')]);S={settings:q[0].data,levels:q[1].data||[],players:q[2].data||[],records:q[3].data||[],points:(q[4].data||[]).map(x=>x.points)};render()}
function render(){
 $('list_name').value=S.settings?.list_name||'';$('tagline').value=S.settings?.tagline||'';
 $('pointsGrid').innerHTML=S.points.map((p,i)=>`<label class="pointInput"><span>#${i+1}</span><input data-rank="${i+1}" type="number" min="0" value="${p}"></label>`).join('');
 renderLevels();
 $('recordPlayer').innerHTML=S.players.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('');
 $('recordLevel').innerHTML=S.levels.map(l=>`<option value="${l.id}">#${l.rank} ${esc(l.name)}</option>`).join('');
 $('playerAdmin').innerHTML=S.players.map(p=>`<div class="adminRow row between"><span>${esc(p.name)}</span><button class="danger" onclick="deletePlayer('${p.id}')">Delete</button></div>`).join('');
 $('recordAdmin').innerHTML=S.records.map(r=>`<div class="adminRow row between"><span>${esc(r.players?.name||'')} → #${S.levels.find(l=>l.id===r.level_id)?.rank||'?'} <span class="meta">${r.video_url?'video':'no video'}</span></span><button class="danger" onclick="deleteRecord('${r.id}')">Remove victory</button></div>`).join('');
}
function renderLevels(){const f=($('levelFilter').value||'').toLowerCase(),sec=$('adminSection').value;const a=S.levels.filter(l=>(sec==='all'||l.section===sec)&&[l.name,l.creator,l.verifier,l.holder,l.difficulty,l.status,l.aliases,l.notes].join(' ').toLowerCase().includes(f));$('levelEditor').innerHTML=a.map(l=>`<article class="adminRow"><div class="row between"><strong>#${l.rank} · ${esc(l.name)}</strong><div class="row"><button class="secondary" onclick="editLevel('${l.id}')">Edit</button><button class="danger" onclick="deleteLevel('${l.id}')">Delete</button></div></div><div class="meta">${esc(l.section)} · ${esc(l.creator||'')} · ${esc(l.verifier||'')} · ${esc(l.holder||'')} · ${esc(l.difficulty||'')} · ${esc(l.status||'')}</div></article>`).join('')||'<div class="panel">No matching levels.</div>'}
async function editLevel(id){const l=S.levels.find(x=>x.id===id);const name=prompt('Level name',l.name);if(name===null)return;const rank=Number(prompt('New rank / placement',l.rank));if(!rank)return;const section=prompt('Section: main, extended, or legacy',l.section);if(!['main','extended','legacy'].includes(section))return alert('Invalid section');const creator=prompt('Creator (optional)',l.creator||'');const verifier=prompt('Verifier (optional)',l.verifier||'');const holder=prompt('Holder (optional)',l.holder||'');const desc=prompt('Description (optional)',l.description||'');const video=prompt('Level verification video URL (optional)',l.video_url||'');const thumb=prompt('Thumbnail URL (optional)',l.thumbnail_url||'');const difficulty=prompt('Difficulty/status tag (optional)',l.difficulty||'');const status=prompt('Status tag (optional)',l.status||'');const aliases=prompt('Aliases (optional)',l.aliases||'');const notes=prompt('Notes (optional)',l.notes||'');const {error}=await sb.rpc('move_level',{p_level_id:id,p_new_section:section,p_new_rank:rank,p_name:name,p_creator:creator,p_verifier:verifier,p_holder:holder,p_description:desc,p_video_url:video,p_thumbnail_url:thumb});if(error){alert(error.message);return}const {error:e2}=await sb.from('levels').update({difficulty:difficulty||null,status:status||null,aliases:aliases||null,notes:notes||null}).eq('id',id);if(e2)alert(e2.message);await load()}
async function newLevel(){const name=prompt('Level name');if(!name)return;const section=prompt('Section: main, extended, legacy','main');if(!['main','extended','legacy'].includes(section))return;const rank=Number(prompt('Placement / rank',section==='main'?S.levels.filter(l=>l.section==='main').length+1:section==='extended'?46:101));if(!rank)return;const {error}=await sb.rpc('create_level',{p_section:section,p_rank:rank,p_name:name});if(error)alert(error.message);else await load()}
async function deleteLevel(id){if(!confirm('Delete this level?'))return;const {error}=await sb.from('levels').delete().eq('id',id);if(error)alert(error.message);else await load()}
async function deletePlayer(id){if(!confirm('Delete player and their victories?'))return;const {error}=await sb.from('players').delete().eq('id',id);if(error)alert(error.message);else await load()}
async function deleteRecord(id){if(!confirm('Remove this victory? Points will disappear automatically.'))return;const {error}=await sb.from('records').delete().eq('id',id);if(error)alert(error.message);else await load()}
$('settingsForm').onsubmit=async e=>{e.preventDefault();const {error}=await sb.from('list_settings').update({list_name:$('list_name').value,tagline:$('tagline').value}).eq('id',S.settings.id);if(error)alert(error.message);else await load()};
$('pointsForm').onsubmit=async e=>{e.preventDefault();for(const inp of document.querySelectorAll('#pointsGrid input')){const {error}=await sb.from('point_values').update({points:Number(inp.value)}).eq('rank',Number(inp.dataset.rank));if(error){alert(error.message);return}}await load()};
$('playerForm').onsubmit=async e=>{e.preventDefault();const {error}=await sb.from('players').insert({name:$('playerName').value.trim()});if(error)alert(error.message);else{$('playerName').value='';await load()}};
$('recordForm').onsubmit=async e=>{e.preventDefault();const {error}=await sb.from('records').upsert({player_id:$('recordPlayer').value,level_id:$('recordLevel').value,progress:Number($('recordProgress').value),video_url:$('recordVideo').value||null},{onConflict:'player_id,level_id'});if(error)alert(error.message);else{$('recordVideo').value='';await load()}};
$('newLevelBtn').onclick=newLevel;$('levelFilter').oninput=renderLevels;$('adminSection').onchange=renderLevels;
$('exportBtn').onclick=()=>{const blob=new Blob([JSON.stringify(S,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='diddy-backup.json';a.click();URL.revokeObjectURL(a.href)};
$('importBtn').onclick=()=>alert('Use the exported JSON as a backup. A transactional restore can be added later.');
async function boot(){if(!sb){msg('Put your Supabase URL + anon/publishable key into config.js first.',false);return}const {data:{user}}=await sb.auth.getUser();if(!user){$('auth').innerHTML='<div class="panel"><h2>Admin login</h2><form id="login"><input id="email" type="email" placeholder="Email" required><input id="password" type="password" placeholder="Password" required><button>Sign in</button></form></div>';$('login').onsubmit=async e=>{e.preventDefault();const {error}=await sb.auth.signInWithPassword({email:$('email').value,password:$('password').value});if(error)msg(error.message,false);else location.reload()};return}const {data:ok}=await sb.rpc('is_admin');if(!ok){msg('Signed in, but this account is not an admin.',false);return}$('adminApp').hidden=false;await load()}boot();
