const cfg=window.DIDDY_CONFIG||window.SUPABASE_CONFIG||{};const url=cfg.SUPABASE_URL||cfg.supabaseUrl||window.SUPABASE_URL||'';const key=cfg.SUPABASE_ANON_KEY||cfg.SUPABASE_KEY||cfg.supabaseAnonKey||window.SUPABASE_ANON_KEY||'';const sb=url&&key&&window.supabase?supabase.createClient(url,key):null;
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let P=[],L=[],R=[],PV=[],H=[],PH=[];
const pts=l=>Number(PV.find(x=>Number(x.rank)===Number(l?.rank))?.points||0);
function playerStats(p){const rs=R.filter(r=>r.player_id===p.id).map(r=>({...r,l:L.find(x=>x.id===r.level_id)})).filter(x=>x.l);const placements=rs.map(x=>x.l.rank);const points=rs.reduce((s,x)=>s+pts(x.l),0),top10=rs.filter(x=>x.l.rank<=10).length,top25=rs.filter(x=>x.l.rank<=25).length;const avg=placements.length?placements.reduce((a,b)=>a+b,0)/placements.length:null;const peak=placements.length?Math.min(...placements):null;const depth=rs.length?Math.max(...placements):0;const consistency=Math.round(Math.max(0,100-(avg||100)*1.7));const power=Math.round(points*2.4+top10*22+top25*8+rs.length*5+consistency);return{rs,points,top10,top25,avg,peak,depth,consistency,power}};
function latestHistoryAt(levelId,cutoff){const rows=PH.filter(x=>x.level_id===levelId&&new Date(x.recorded_at)<=cutoff).sort((a,b)=>new Date(b.recorded_at)-new Date(a.recorded_at));return rows[0]||null}
function historicalRows(cutoff){return L.map(l=>{const h=latestHistoryAt(l.id,cutoff);return h?{...l,section:h.section,rank:h.rank,points:h.points,historical:true}:{...l,historical:false}}).filter(x=>x.historical||new Date(x.created_at||0)<=cutoff).sort((a,b)=>a.rank-b.rank)}
function rankChangeMap(){const out={};for(const l of L){const hs=PH.filter(h=>h.level_id===l.id).sort((a,b)=>new Date(a.recorded_at)-new Date(b.recorded_at));if(hs.length){out[l.id]={first:hs[0].rank,last:hs.at(-1).rank,delta:hs[0].rank-hs.at(-1).rank};}}return out}
function reigns(){const by={};PH.filter(h=>Number(h.rank)===1).forEach(h=>(by[h.level_id]??=[]).push(h));return Object.entries(by).map(([id,rows])=>{rows.sort((a,b)=>new Date(a.recorded_at)-new Date(b.recorded_at));let best=0,bestFrom=null,bestTo=null;for(let i=0;i<rows.length;i++){const from=new Date(rows[i].recorded_at),next=rows[i+1]?.recorded_at?new Date(rows[i+1].recorded_at):new Date();const days=(next-from)/86400000;if(days>best){best=days;bestFrom=from;bestTo=next}}return{l:L.find(x=>x.id===id),days:best,from:bestFrom,to:bestTo}}).filter(x=>x.l).sort((a,b)=>b.days-a.days)}
function metricCard(icon,title,value,sub){return `<div class="hallMetric"><span>${icon}</span><b>${value}</b><small>${title}</small><em>${sub||''}</em></div>`}
function autoCategories(){const ps=P.map(p=>({...p,s:playerStats(p)})).sort((a,b)=>b.s.power-a.s.power), decorated=P.map(p=>({...p,s:playerStats(p)})).sort((a,b)=>b.s.rs.length-a.s.rs.length||b.s.points-a.s.points), victories=R.map(r=>({...r,p:P.find(x=>x.id===r.player_id),l:L.find(x=>x.id===r.level_id)})).filter(x=>x.p&&x.l).sort((a,b)=>a.l.rank-b.l.rank), rc=rankChangeMap(), climbers=L.map(l=>({...l,c:rc[l.id]})).filter(x=>x.c&&x.c.delta>0).sort((a,b)=>b.c.delta-a.c.delta), drops=L.map(l=>({...l,c:rc[l.id]})).filter(x=>x.c&&x.c.delta<0).sort((a,b)=>a.c.delta-b.c.delta), oldest=victories.slice().sort((a,b)=>new Date(a.created_at)-new Date(b.created_at))[0], hardest=victories[0], attempts=R.filter(r=>r.attempts!=null).map(r=>({...r,p:P.find(x=>x.id===r.player_id),l:L.find(x=>x.id===r.level_id)})).filter(x=>x.p&&x.l).sort((a,b)=>a.attempts-b.attempts),speed=R.filter(r=>r.completion_seconds!=null).map(r=>({...r,p:P.find(x=>x.id===r.player_id),l:L.find(x=>x.id===r.level_id)})).filter(x=>x.p&&x.l).sort((a,b)=>a.completion_seconds-b.completion_seconds),reigns=reigns();
return{ps,decorated,victories,climbers,drops,oldest,hardest,attempts,speed,reigns};}
function row(text,right=''){return `<div class="adminRow row between"><span>${text}</span><strong>${right}</strong></div>`}
function render(){const C=autoCategories();$('hallMetrics').innerHTML=metricCard('👑','most powerful',C.ps[0]?.name||'—',C.ps[0]?`${C.ps[0].s.power} Power`: 'No players')+metricCard('🏆','most victories',C.decorated[0]?.name||'—',C.decorated[0]?`${C.decorated[0].s.rs.length} wins`:'No victories')+metricCard('🧗','biggest climber',C.climbers[0]?`#${C.climbers[0].rank} ${C.climbers[0].name}`:'—',C.climbers[0]?`+${C.climbers[0].c.delta} ranks`:'Need history')+metricCard('🕰️','longest #1 reign',C.reigns[0]?.l?`#${C.reigns[0].l.rank} ${C.reigns[0].l.name}`:'—',C.reigns[0]?`${Math.round(C.reigns[0].days)} days`:'Need history');
$('autoHall').innerHTML=`<section class="panel"><p class="eyebrow">GREATEST PLAYERS</p><h2>👑 Power Kings</h2>${C.ps.slice(0,10).map((x,i)=>row(`<a href="player.html?id=${x.id}"><b>#${i+1} ${esc(x.name)}</b> <span class="meta">${x.s.rs.length} victories · peak #${x.s.peak??'—'}</span></a>`,`⚡ ${x.s.power}`)).join('')||'<p class="meta">No players yet.</p>'}</section>
<section class="panel"><p class="eyebrow">LEGENDARY VICTORIES</p><h2>💀 Hardest wins</h2>${C.victories.slice(0,12).map(x=>row(`<a href="level.html?id=${x.l.id}"><b>#${x.l.rank} ${esc(x.l.name)}</b></a> <span class="meta">by <a href="player.html?id=${x.p.id}">${esc(x.p.name)}</a></span>`,`${pts(x.l)} pts`)).join('')||'<p class="meta">No victories yet.</p>'}</section>
<section class="panel"><p class="eyebrow">CLIMB / FALL</p><h2>📈 Biggest rank climbers</h2>${C.climbers.slice(0,8).map(x=>row(`<a href="level.html?id=${x.id}"><b>#${x.rank} ${esc(x.name)}</b></a> <span class="meta">was #${x.c.first}</span>`,`+${x.c.delta}`)).join('')||'<p class="meta">Not enough placement history yet.</p>'}<h3>📉 Biggest falls</h3>${C.drops.slice(0,8).map(x=>row(`<a href="level.html?id=${x.id}"><b>#${x.rank} ${esc(x.name)}</b></a> <span class="meta">was #${x.c.first}</span>`,`${x.c.delta}`)).join('')||'<p class="meta">Not enough placement history yet.</p>'}</section>
<section class="panel"><p class="eyebrow">RECORD BOOK</p><h2>🌎 Global records</h2>${C.oldest?row(`🩸 <b>First recorded victory</b> · ${esc(C.oldest.p.name)} on #${C.oldest.l.rank} ${esc(C.oldest.l.name)}`,new Date(C.oldest.created_at).toLocaleDateString()):''}${C.hardest?row(`☢️ <b>Hardest recorded victory</b> · ${esc(C.hardest.p.name)} on #${C.hardest.l.rank}`,`${pts(C.hardest.l)} pts`):''}${C.attempts[0]?row(`🎯 <b>Fewest attempts</b> · ${esc(C.attempts[0].p.name)} on #${C.attempts[0].l.rank}`,`${Number(C.attempts[0].attempts).toLocaleString()} attempts`):''}${C.speed[0]?row(`⚡ <b>Fastest completion</b> · ${esc(C.speed[0].p.name)} on #${C.speed[0].l.rank}`,`${Number(C.speed[0].completion_seconds).toFixed(1)}s`):''}</section>
<section class="panel"><p class="eyebrow">LONGEST REIGNS</p><h2>🕰️ #1 Reign Records</h2>${C.reigns.slice(0,8).map(x=>row(`<a href="level.html?id=${x.l.id}"><b>#1 ${esc(x.l.name)}</b></a>`,`${Math.round(x.days)} days`)).join('')||'<p class="meta">Placement history has not recorded a #1 change yet.</p>'}</section>`;
$('customHall').innerHTML=H.length?H.map(x=>`<article class="hallCustom"><span class="tag">${esc(x.category)}</span><h3>${esc(x.title)}</h3><p>${esc(x.body)}</p><div class="meta">${x.year||'Undated'}${x.player_id?` · <a href="player.html?id=${x.player_id}">player</a>`:''}${x.level_id?` · <a href="level.html?id=${x.level_id}">level</a>`:''}</div></article>`).join(''):'<p class="meta">No curated entries yet. Admins can add legends.</p>';
$('challenge').innerHTML=dailyChallenge();}
function dailyChallenge(){if(!L.length)return '<p class="meta">Add levels to generate today\'s challenge.</p>';const day=Math.floor(Date.now()/86400000),l=L.slice().sort((a,b)=>a.rank-b.rank)[day%L.length];return `<div class="challengeBox"><span class="eyebrow">TODAY'S CHALLENGE</span><h2>🎲 Beat <a href="level.html?id=${l.id}">#${l.rank} ${esc(l.name)}</a></h2><p>Fun/unofficial challenge. No official points are awarded for this card.</p><button class="secondary" onclick="navigator.clipboard?.writeText(location.origin+location.pathname.replace('hall.html','')+'level.html?id=${l.id}')">📋 Copy challenge</button></div>`}
function renderTimeMachine(){const val=$('historyDate').value;if(!val){$('historyOut').innerHTML='<p class="meta">Pick a date to view the recorded list.</p>';return}const cutoff=new Date(val+'T23:59:59');const rows=historicalRows(cutoff);$('historyOut').innerHTML=`<div class="listSummary"><span><b>${rows.length}</b> levels reconstructed</span><span>Snapshot: <b>${cutoff.toLocaleDateString()}</b></span></div>${rows.slice(0,100).map(x=>`<div class="adminRow row between"><span><b>#${x.rank} ${esc(x.name)}</b><span class="meta"> · ${esc(x.section)}</span></span><strong>${Number(x.points||pts(x)).toLocaleString()} pts</strong></div>`).join('')||'<p class="meta">No recorded placements existed by that date.</p>'}`}
async function boot(){if(!sb){$('hall').innerHTML='<div class="panel">Configure Supabase first.</div>';return}const q=await Promise.all([sb.from('players').select('*'),sb.from('levels').select('*').order('rank'),sb.from('records').select('*'),sb.from('point_values').select('*').order('rank'),sb.from('hall_entries').select('*').order('created_at',{ascending:false}),sb.from('placement_history').select('*').order('recorded_at')]);const bad=q.find(x=>x.error);if(bad?.error){$('hall').innerHTML=`<div class="panel error">${esc(bad.error.message)}<p class="meta">If this mentions hall_entries, run v13_schema_patch.sql once.</p></div>`;return}[P,L,R,PV,H,PH]=q.map(x=>x.data||[]);render();$('historyDate').max=new Date().toISOString().slice(0,10);$('historyDate').value=new Date().toISOString().slice(0,10);renderTimeMachine();$('historyDate').onchange=renderTimeMachine;}
boot();
