const cfg=window.DIDDY_CONFIG||{};const sb=cfg.SUPABASE_URL&&cfg.SUPABASE_ANON_KEY?supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY):null;
const id=new URLSearchParams(location.search).get('id');const $=x=>document.getElementById(x);const esc=s=>String(s??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;');
async function boot(){if(!sb){$('levelPage').innerHTML='<div class="panel">Connect Supabase in config.js first.</div>';return}
 const q=await Promise.all([sb.from('levels').select('*').eq('id',id).single(),sb.from('records').select('*,players(name)').eq('level_id',id).order('created_at',{ascending:true}),sb.from('placement_history').select('*').eq('level_id',id).order('recorded_at',{ascending:true}),sb.from('point_values').select('*')]);
 const l=q[0].data;if(q[0].error){$('levelPage').innerHTML='<div class="panel">Level not found.</div>';return}
 const points=Object.fromEntries((q[3].data||[]).map(x=>[x.rank,x.points])),wins=q[1].data||[],hist=q[2].data||[],ranks=hist.map(h=>h.rank),highest=ranks.length?Math.min(...ranks):l.rank,lowest=ranks.length?Math.max(...ranks):l.rank,dates=hist.map(h=>new Date(h.recorded_at).toLocaleDateString()),histRanks=ranks.length?ranks:[l.rank];
 const victorHtml=wins.map(x=>`<div class="adminRow row between"><a href="player.html?id=${x.player_id}"><strong>${esc(x.players?.name||'Unknown')}</strong></a><span class="meta">${x.progress||100}% · ${x.video_url?`<a href="${esc(x.video_url)}" target="_blank">video</a>`:'no video'} · ${x.created_at?new Date(x.created_at).toLocaleDateString():''}</span></div>`).join('')||'<p class="muted">No victors yet.</p>';
 const histHtml=hist.slice().reverse().map(h=>`<div class="timelineItem"><div class="timelineDot"></div><div><strong>#${h.rank}</strong> · ${h.points} pts <span class="muted">· ${new Date(h.recorded_at).toLocaleString()}</span><div class="small muted">${esc(h.note||'Placement update')}</div></div></div>`).join('')||'<p class="muted">No recorded placement changes yet.</p>';
 const video=l.video_url?`<a class="btn" target="_blank" href="${esc(l.video_url)}">▶ Verification video</a>`:'<span class="muted">No verification video</span>';
 $('levelPage').innerHTML=`<section class="hero levelHero"><div>${l.thumbnail_url?`<img class="levelHeroThumb" src="${esc(l.thumbnail_url)}" alt="">`:''}<div><p class="eyebrow">#${l.rank} · ${esc(l.section).toUpperCase()}</p><h1>${esc(l.name)}</h1><p>${esc(l.description||'No description added yet.')}</p><div class="tagRow">${[l.difficulty,l.status].filter(Boolean).map(x=>`<span class="tag">${esc(x)}</span>`).join('')}</div></div></div><div class="heroStats"><div><b>${points[l.rank]||0}</b><span>points</span></div><div><b>${wins.length}</b><span>victors</span></div></div></section><section class="profileStats"><div class="stat"><span class="muted">Current placement</span><strong>#${l.rank}</strong></div><div class="stat"><span class="muted">Highest placement</span><strong>#${highest}</strong></div><div class="stat"><span class="muted">Lowest placement</span><strong>#${lowest}</strong></div><div class="stat"><span class="muted">Times ranked</span><strong>${Math.max(hist.length,1)}</strong></div></section><section class="panel"><div class="grid"><div class="stat"><span class="muted">Creator</span><strong>${esc(l.creator||'—')}</strong></div><div class="stat"><span class="muted">Verifier</span><strong>${esc(l.verifier||'—')}</strong></div><div class="stat"><span class="muted">Holder</span><strong>${esc(l.holder||'—')}</strong></div><div class="stat"><span class="muted">Added</span><strong>${l.created_at?new Date(l.created_at).toLocaleDateString():'—'}</strong></div></div><p>${video}</p>${l.aliases?`<p class="meta">Aliases: ${esc(l.aliases)}</p>`:''}${l.notes?`<p class="meta">${esc(l.notes)}</p>`:''}</section><section class="panel"><div class="sectionTitle"><div><p class="eyebrow">PLACEMENT MOVEMENT</p><h2>Rank history</h2></div></div><div class="chartBox"><canvas id="levelChart"></canvas></div></section><section class="panel"><h2>Victors</h2><div class="list">${victorHtml}</div></section><section class="panel"><h2>Placement timeline</h2><div class="timeline">${histHtml}</div></section>`;
 if(window.Chart){new Chart($('levelChart'),{type:'line',data:{labels:dates.length?dates:['Current'],datasets:[{label:'Rank',data:histRanks,borderColor:'#ffcf5c',backgroundColor:'rgba(255,207,92,.12)',fill:true,tension:.25,pointRadius:5}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{labels:{color:'#cbd0e4'}}},scales:{y:{reverse:true,beginAtZero:false,ticks:{color:'#9da4bd',precision:0},grid:{color:'rgba(157,164,189,.08)'}},x:{ticks:{color:'#9da4bd'},grid:{color:'rgba(157,164,189,.08)'}}}}});}
}boot();
