const cfg=window.DIDDY_CONFIG||{};const sb=cfg.SUPABASE_URL&&cfg.SUPABASE_ANON_KEY?supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY):null;
const id=new URLSearchParams(location.search).get('id');const esc=s=>String(s??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;');
async function boot(){const el=document.getElementById('playerPage');if(!sb){el.innerHTML='<div class="panel">Connect Supabase first.</div>';return}
 const q=await Promise.all([sb.from('players').select('*').eq('id',id).single(),sb.from('records').select('*').eq('player_id',id).order('created_at',{ascending:true}),sb.from('levels').select('*'),sb.from('point_values').select('*'),sb.from('player_leaderboard').select('*')]);
 const p=q[0].data;if(q[0].error){el.innerHTML='<div class="panel">Player not found.</div>';return}
 const points=Object.fromEntries((q[3].data||[]).map(x=>[x.rank,x.points])),map=Object.fromEntries((q[2].data||[]).map(x=>[x.id,x])),wins=(q[1].data||[]).map(x=>({...x,level:map[x.level_id]})).filter(x=>x.level).sort((a,b)=>a.level.rank-b.level.rank),total=wins.reduce((s,x)=>s+(points[x.level.rank]||0),0),best=wins[0]?.level.rank??'—',worst=wins.at(-1)?.level.rank??'—',avg=wins.length?(wins.reduce((s,x)=>s+x.level.rank,0)/wins.length).toFixed(1):'—',sorted=(q[4].data||[]).sort((a,b)=>b.total_points-a.total_points),current=sorted.findIndex(x=>x.id===id)+1;
 let winsHtml=wins.map(w=>`<a class="levelCard polishedLevelCard" href="level.html?id=${w.level.id}"><div class="thumb"><span class="thumbPlaceholder">#${w.level.rank}</span></div><div class="levelMain"><div class="rank">#${w.level.rank} · ${points[w.level.rank]||0} points</div><div class="levelTitle">${esc(w.level.name)}</div><div class="meta">${w.progress||100}% completion · ${w.video_url?'video attached':'no video attached'} · ${w.created_at?new Date(w.created_at).toLocaleDateString():'date unknown'}</div></div><div class="points"><strong>${points[w.level.rank]||0}</strong><small>points</small></div></a>`).join('');if(!winsHtml)winsHtml='<p class="muted">No victories yet.</p>';
 const labels=wins.map(w=>`#${w.level.rank}`),vals=wins.map(w=>points[w.level.rank]||0);
 el.innerHTML=`<section class="hero profileHero"><div><p class="eyebrow">PLAYER PROFILE · #${current||'—'}</p><h1>${esc(p.name)}</h1><p>Live statistics calculated from recorded victories.</p></div><div class="heroStats"><div><b>${total.toLocaleString()}</b><span>points</span></div><div><b>${wins.length}</b><span>victories</span></div></div></section><section class="profileStats"><div class="stat"><span class="muted">Leaderboard rank</span><strong>#${current||'—'}</strong></div><div class="stat"><span class="muted">Highest victory</span><strong>#${best}</strong></div><div class="stat"><span class="muted">Lowest victory</span><strong>#${worst}</strong></div><div class="stat"><span class="muted">Average placement</span><strong>${avg}</strong></div></section><section class="panel"><div class="sectionTitle"><div><p class="eyebrow">VICTORY POWER</p><h2>Points earned by victory</h2></div></div><div class="chartBox"><canvas id="playerChart"></canvas></div></section><section class="panel"><div class="sectionTitle"><div><p class="eyebrow">VICTORY HISTORY</p><h2>${wins.length} recorded victories</h2></div></div><div class="list">${winsHtml}</div></section>`;
 if(window.Chart&&wins.length){new Chart(document.getElementById('playerChart'),{type:'bar',data:{labels,datasets:[{label:'Points',data:vals,backgroundColor:'#7c6cff',borderRadius:8}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{x:{ticks:{color:'#9da4bd'}},y:{ticks:{color:'#9da4bd'},beginAtZero:true,grid:{color:'rgba(157,164,189,.08)'}}}}});}
}boot();
