// RELEASE NOTES SOURCE OF TRUTH
// For every future site update, add ONE new object at the TOP of this array.
// Keep the newest release first. Do not delete older releases.
window.DIDDY_RELEASE_NOTES=[{version:'2.4.4',date:'2026-09-13T00:00:00Z',title:'V2.4.4 — DIDDY ERAS 3.0',body:'Rebuilt Diddy Eras into real historical chapters with automatic period clustering, named dominant-player eras, victory and #1-level statistics, era points, ranking activity, active levels, and historical memory highlights. Seasons remain intentionally excluded.'},
{version:'2.4.2',date:'2026-09-13T00:00:00Z',title:'V2.4.2 — THE INTELLIGENCE UPDATE',body:'Added Power Rankings 2.0 with current-vs-previous 3-day position tracking, Diddy Intelligence, Level Heat, smarter Feed filters, Search 5.5 combined queries, Achievement Trophy Cabinet, Battle Intelligence, Time Machine playback, named Era intelligence, 30-day Player Momentum, and recent record alerts. No seasons and no new Supabase schema required.'},
{version:'2.4.1.3',date:'2026-09-09T00:00:00Z',title:'V2.4.1.3 — CAREER TIMELINE HOTFIX',body:'Fixed the Career Timeline selector so Easiest → hardest, Hardest → easiest, and Highest points → lowest points are no longer overwritten by the legacy timeline listener.'},
{version:'2.4.1.2',date:'2026-09-08T00:00:00Z',title:'V2.4.1.2 — RANKING REPAIR FIX',body:'Fixed existing rank gaps after level deletion, added a server-side global ranking repair, and added an admin Repair rankings tool.'},
  {version:'2.4.1',date:'2026-09-08T00:00:00Z',title:'V2.4.1 — RANKING INTEGRITY FIX',body:'Fixed rank gaps after deleting levels and prevented accidental duplicate level creation from repeated form submissions.'},

  {date:'2026-09-09T00:00:00Z',title:'V2.4.0 — THE LEGACY UPDATE',body:'Added Player Profiles 7.0 career legacy tools, daily player-rank reconstruction, four Career Timeline modes, Level Profiles 6.0 history and eras, Diddy Feed 4.0 filters and event cards, Search 5.0 combined queries, Record Book 5.0 historical records, Time Machine 4.0 period intelligence, Diddy Eras 3.0 named activity eras, and Diddy Power Rankings. No seasons, no config changes, and no new Supabase schema required.'},
  {date:'2026-09-08T00:00:00Z',title:'V2.3.3 — LIVE DIDDY FEED CLEANUP',body:'Reduced the Live Diddy Feed height and stopped the homepage layout from stretching the feed into a giant panel beside Recent Victories. This is a small visual cleanup with no feature removals.'},
  {date:'2026-09-09T00:00:00Z',title:'V2.3.2 — DAILY RANK MOVEMENT & TIMELINE SORTING',body:'Fixed Career Rank Movement to reconstruct the player leaderboard position every calendar day from recorded victories and list history. Added Career Timeline sorting for beat order and least-to-hardest. Existing features remain preserved.'},
  {date:'2026-09-08T00:00:00Z',title:'V2.3.1 — EVOLUTION EXPANSION',body:'Expanded the Evolution update with career highlights, level career analytics, richer live event cards, achievement progress tracking, deeper battle scoring, query-style search, expanded records, and a more alive homepage.'},
  {date:'2026-09-08T00:00:00Z',title:'V2.3 — THE EVOLUTION UPDATE',body:'Added Career Intel for player and level pages, with career highlights, activity streaks, best-month tracking, movement milestones, median attempts, timed-run highlights, and a fast 7-day level pulse. No existing features were removed.'},
  {date:'2026-09-07T00:00:00Z',title:'V2.2.3 — THE QUALITY UPDATE',body:'Polished the Diddy Daily Briefing with a real 24-hour summary, quiet-day messaging, biggest movement callouts, and most-active-player highlights. Cache-busted homepage scripts so the new logic cannot be hidden by stale browser JavaScript.'},
  {date:'2026-09-07T00:00:00Z',title:'V2.2.2 — DAILY BRIEFING FIX',body:'Fixed the homepage Diddy Daily Briefing so its generated summary is actually rendered on page load. The briefing now shows the current #1 level, #1 player, recent 24-hour movement, and hot recent victory activity when available.'},
  {date:'2026-09-08T00:00:00Z',title:'V2.2 — THE DYNASTY UPDATE · FOUNDATION',body:'Started the V2.2 major update. Fixed the Players page rendering regression, restored working Form Score and Player Titles on player cards, and documented the release while preserving existing features.'},
  {date:'2026-09-07T00:00:00Z',title:'V2.1 — THE DIDDY ERA UPDATE',body:'Added Player Form 2.0, Form Score, Player Titles, Player Rank History, Level Momentum, Diddy Daily Briefing, Record Breaker Alerts, Rivalry History, Search 4.0 foundations, List Health navigation, and Diddy Eras. Seasons are intentionally excluded.'},
  {date:'2026-09-06T00:00:00Z',title:'V2.0.4 — PLAYER FORM THRESHOLD',body:'Adjusted Player Form so SURGING requires 6 or more victories in the last 24 hours plus clear acceleration versus the previous 24 hours. RISING, ACTIVE, COOLING, and QUIET remain based on the same 24-hour comparison window.'},
  {date:'2026-09-03T00:00:00Z',title:'V2.0.3 — RANK HISTORY & MOVEMENT',body:'Added reliable 24-hour rank movement badges on level rows, records every level displaced by a move so movement indicators appear consistently, and tightened movement tracking for new level insertions.'}
];
