const cfg=window.DIDDY_CONFIG||{};const sb=cfg.SUPABASE_URL&&cfg.SUPABASE_ANON_KEY?supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY):null;
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const n=(x,d=0)=>Number.isFinite(Number(x))?Number(x):d;
const pts=(rank,map)=>n(map[n(rank)],Math.max(1,101-n(rank)));
const sec=s=>s==='main'?'Main':s==='extended'?'Extended':'Legacy';
const date=x=>x?new Date(x).toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'}):'—';
let charts=[];
function destroyCharts(){charts.forEach(c=>c.destroy());charts=[]}
function makeChart(id,type,data,options={}){const el=$(id);if(!el||!window.Chart)return;const c=new Chart(el.getContext('2d'),{type,data,options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{labels:{color:'#cbd0e4'}},tooltip:{mode:'index',intersect:false}},scales:type==='pie'?{}:{x:{ticks:{color:'#9da4bd'},grid:{color:'rgba(157,164,189,.08)'}},y:{ticks:{color:'#9da4bd'},grid:{color:'rgba(157,164,189,.08)'},beginAtZero:true}},...options}});charts.push(c);return c}
function color(i){const c=['#7c6cff','#62e58a','#ffcf5c','#67c7ff','#ff7f9d','#b993ff','#54e0cf','#ff9f66'];return c[i%c.length]}
async function boot(){const root=$('stats');if(!sb){root.innerHTML='<div class="panel error">Connect Supabase to calculate live statistics.</div>';return}
try{const qs=await Promise.all([sb.from('levels').select('*'),sb.from('records').select('*'),sb.from('players').select('*'),sb.from('point_values').select('rank,points'),sb.from('player_leaderboard').select('*'),sb.from('placement_history').select('*').order('recorded_at',{ascending:true})]);const err=qs.find(q=>q.error);if(err?.error)throw err.error;
const L=qs[0].data||[],R=qs[1].data||[],P=qs[2].data||[],PM=Object.fromEntries((qs[3].data||[]).map(x=>[x.rank,x.points])),LB=qs[4].data||[],H=qs[5].data||[];
const byL=Object.fromEntries(L.map(x=>[x.id,x])),byP=Object.fromEntries(P.map(x=>[x.id,x]));const vc={};R.forEach(r=>vc[r.level_id]=(vc[r.level_id]||0)+1);const pv={};R.forEach(r=>pv[r.player_id]=(pv[r.player_id]||0)+1);
const scored=L.map(l=>({...l,points:pts(l.rank,PM),victors:n(vc[l.id])}));const ranked=LB.slice().sort((a,b)=>n(b.total_points)-n(a.total_points)||n(a.highest_victory,999)-n(b.highest_victory,999));
const totalPoints=R.reduce((s,r)=>s+pts(byL[r.level_id]?.rank,PM),0),uniqueVictors=new Set(R.map(r=>r.player_id)).size;
const avgRank=R.length?R.reduce((s,r)=>s+n(byL[r.level_id]?.rank),0)/R.length:0;const avgPts=R.length?totalPoints/R.length:0;
const difficulty={};scored.forEach(l=>{difficulty[l.difficulty||'Unspecified']=(difficulty[l.difficulty||'Unspecified']||0)+1});
const status={};scored.forEach(l=>{status[l.status||'Unspecified']=(status[l.status||'Unspecified']||0)+1});
const main=L.filter(x=>x.section==='main').length,ext=L.filter(x=>x.section==='extended').length,legacy=L.filter(x=>x.section==='legacy').length;
const recentWins=R.slice().sort((a,b)=>new Date(b.created_at||0)-new Date(a.created_at||0));
const levelStats=scored.slice().sort((a,b)=>b.victors-a.victors||a.rank-b.rank),topLevels=scored.slice().sort((a,b)=>a.rank-b.rank).slice(0,10);
root.innerHTML=`
<div class="v7Kpis"><div class="v7Kpi"><span>Levels</span><b>${L.length}</b><small>${main} main · ${ext} extended · ${legacy} legacy</small></div><div class="v7Kpi"><span>Players</span><b>${P.length}</b><small>${uniqueVictors} with victories</small></div><div class="v7Kpi"><span>Victories</span><b>${R.length}</b><small>${L.length?(R.length/L.length).toFixed(2):'0'} per level</small></div><div class="v7Kpi"><span>Points in circulation</span><b>${totalPoints.toLocaleString()}</b><small>live from current ranks</small></div><div class="v7Kpi"><span>Avg. placement</span><b>${avgRank?avgRank.toFixed(1):'—'}</b><small>lower = harder</small></div><div class="v7Kpi"><span>Avg. victory value</span><b>${avgPts?avgPts.toFixed(1):'—'}</b><small>points per victory</small></div></div>
<section class="panel chartPanel"><div class="sectionTitle"><div><p class="eyebrow">LIST POWER CURVE</p><h2>Points by rank</h2><p class="muted">Hover a rank to inspect its exact point value.</p></div><select id="curveRange"><option value="25">Top 25</option><option value="50">Top 50</option><option value="100" selected>Top 100</option></select></div><div class="chartBox"><canvas id="pointsChart"></canvas></div></section>
<div class="statsGrid twoWide"><section class="panel chartPanel"><div class="sectionTitle"><div><p class="eyebrow">DIFFICULTY</p><h2>Difficulty distribution</h2></div></div><div class="chartBox smallChart"><canvas id="difficultyChart"></canvas></div></section><section class="panel chartPanel"><div class="sectionTitle"><div><p class="eyebrow">LIST STATUS</p><h2>Status distribution</h2></div></div><div class="chartBox smallChart"><canvas id="statusChart"></canvas></div></section></div>
<section class="panel comparePanel"><div class="sectionTitle"><div><p class="eyebrow">PLAYER VS PLAYER</p><h2>Head-to-head comparison</h2><p class="muted">Pick any two players and compare points, victories, best rank, and average placement.</p></div></div><div class="compareControls"><select id="playerA"></select><span>VS</span><select id="playerB"></select></div><div id="compareCards" class="compareCards"></div><div class="chartBox compareChart"><canvas id="compareChart"></canvas></div></section>
<section class="panel chartPanel"><div class="sectionTitle"><div><p class="eyebrow">RANK MOVEMENT</p><h2>Level placement history</h2><p class="muted">Choose a level to see every recorded placement change.</p></div><select id="movementLevel"></select></div><div id="movementSummary" class="movementSummary"></div><div class="chartBox"><canvas id="movementChart"></canvas></div></section>
<div class="statsGrid twoWide"><section class="panel"><div class="sectionTitle"><div><p class="eyebrow">LEVEL ANALYTICS</p><h2>Most victored levels</h2></div></div><div class="analyticsList">${levelStats.slice(0,12).map((l,i)=>`<a href="level.html?id=${encodeURIComponent(l.id)}" class="analyticsRow"><span class="place">#${l.rank}</span><span class="aName">${esc(l.name)}<small>${sec(l.section)} · ${l.points} pts</small></span><b>${l.victors}</b><em>victors</em></a>`).join('')||'<p class="muted">No levels yet.</p>'}</div></section><section class="panel"><div class="sectionTitle"><div><p class="eyebrow">VICTORY RECORDS</p><h2>Recent victories</h2></div><span class="muted">${R.length} total</span></div><div class="recordTableWrap"><table class="recordTable"><thead><tr><th>Player</th><th>Level</th><th>Rank</th><th>Points</th><th>Date</th></tr></thead><tbody>${recentWins.slice(0,14).map(r=>`<tr><td><a href="player.html?id=${r.player_id}">${esc(byP[r.player_id]?.name||'Unknown')}</a></td><td><a href="level.html?id=${r.level_id}">${esc(byL[r.level_id]?.name||'Unknown')}</a></td><td>#${n(byL[r.level_id]?.rank)}</td><td>${pts(byL[r.level_id]?.rank,PM)}</td><td>${date(r.created_at)}</td></tr>`).join('')||'<tr><td colspan="5" class="muted">No victories yet.</td></tr>'}</tbody></table></div></section></div>
<section class="panel hallPanel"><div class="sectionTitle"><div><p class="eyebrow">HALL OF FAME</p><h2>The DIDDY legends</h2><p class="muted">Automatic awards based on the live database.</p></div></div><div class="hallGrid"><div class="hallCard"><span>🏆</span><small>POINT KING</small><a id="hallPoints">—</a><b id="hallPointsValue">0 pts</b></div><div class="hallCard"><span>👑</span><small>MOST VICTORIES</small><a id="hallWins">—</a><b id="hallWinsValue">0 wins</b></div><div class="hallCard"><span>🎯</span><small>BEST AVERAGE</small><a id="hallAvg">—</a><b id="hallAvgValue">— avg.</b></div><div class="hallCard"><span>💀</span><small>MOST BEATEN LEVEL</small><a id="hallLevel">—</a><b id="hallLevelValue">0 victors</b></div><div class="hallCard"><span>⚡</span><small>HIGHEST POINT LEVEL</small><a id="hallTopLevel">—</a><b id="hallTopLevelValue">0 pts</b></div><div class="hallCard"><span>📈</span><small>BEST RECORDED CLIMB</small><a id="hallClimb">—</a><b id="hallClimbValue">—</b></div></div></section>
<section class="panel"><div class="sectionTitle"><div><p class="eyebrow">VICTORY DEPTH</p><h2>Victories by rank band</h2></div></div><div class="chartBox smallChart"><canvas id="bandChart"></canvas></div></section>`;
init(L,R,P,PM,LB,H,byL,byP,scored,difficulty,status,ranked,levelStats);
}catch(e){console.error(e);root.innerHTML=`<div class="panel error"><h2>Stats failed to load</h2><p>${esc(e.message||e)}</p></div>`}}
function init(L,R,P,PM,LB,H,byL,byP,scored,difficulty,status,ranked,levelStats){destroyCharts();
 const pointChart=()=>{const lim=n($('curveRange').value,100);makeChart('pointsChart','line',{labels:Array.from({length:lim},(_,i)=>'#'+(i+1)),datasets:[{label:'Points',data:Array.from({length:lim},(_,i)=>pts(i+1,PM)),borderColor:'#7c6cff',backgroundColor:'rgba(124,108,255,.13)',fill:true,tension:.28,pointRadius:2}]},{plugins:{legend:{display:false}}});};pointChart();$('curveRange').onchange=pointChart;
 const dlabels=Object.keys(difficulty),slabels=Object.keys(status);makeChart('difficultyChart','doughnut',{labels:dlabels,datasets:[{data:dlabels.map(x=>difficulty[x]),backgroundColor:dlabels.map((_,i)=>color(i)),borderColor:'#1b1e2e',borderWidth:3}]});makeChart('statusChart','doughnut',{labels:slabels,datasets:[{data:slabels.map(x=>status[x]),backgroundColor:slabels.map((_,i)=>color(i+3)),borderColor:'#1b1e2e',borderWidth:3}]});
 const pa=$('playerA'),pb=$('playerB');const opts=P.slice().sort((a,b)=>a.name.localeCompare(b.name)).map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('');pa.innerHTML=opts;pb.innerHTML=opts;if(P.length>1)pb.selectedIndex=1;const lbMap=Object.fromEntries(LB.map(x=>[x.id,x]));
 function compare(){const A=lbMap[pa.value]||{name:'—',total_points:0,victors:0,highest_victory:null,average_placement:null},B=lbMap[pb.value]||{name:'—',total_points:0,victors:0,highest_victory:null,average_placement:null};const cards=(x,cls)=>`<div class="compareCard ${cls}"><div class="compareName">${esc(x.name)}</div><div><b>${n(x.total_points).toLocaleString()}</b><small>points</small></div><div><b>${n(x.victors)}</b><small>victories</small></div><div><b>${x.highest_victory?'#'+x.highest_victory:'—'}</b><small>best level</small></div><div><b>${x.average_placement??'—'}</b><small>average placement</small></div></div>`;$('compareCards').innerHTML=cards(A,'a')+cards(B,'b');makeChart('compareChart','bar',{labels:['Points','Victories'],datasets:[{label:A.name,data:[n(A.total_points),n(A.victors)],backgroundColor:'#7c6cff'},{label:B.name,data:[n(B.total_points),n(B.victors)],backgroundColor:'#62e58a'}]},{plugins:{legend:{labels:{color:'#cbd0e4'}}}})}
 pa.onchange=compare;pb.onchange=compare;if(P.length)compare();
 const ml=$('movementLevel');ml.innerHTML=scored.slice().sort((a,b)=>a.rank-b.rank).map(l=>`<option value="${l.id}">#${l.rank} — ${esc(l.name)}</option>`).join('');
 function movement(){const id=ml.value,l=byL[id],hist=H.filter(h=>h.level_id===id).sort((a,b)=>new Date(a.recorded_at)-new Date(b.recorded_at));const rows=hist.length?hist:[{rank:l.rank,points:pts(l.rank,PM),recorded_at:null,note:'Current placement'}];$('movementSummary').innerHTML=`<span><b>${rows.length}</b> recorded placements</span><span>Highest: <b>#${Math.min(...rows.map(x=>n(x.rank,999)))}</b></span><span>Lowest: <b>#${Math.max(...rows.map(x=>n(x.rank,0)))}</b></span><span>Current: <b>#${l.rank}</b></span>`;makeChart('movementChart','line',{labels:rows.map((x,i)=>x.recorded_at?date(x.recorded_at):'Current'),datasets:[{label:'Rank',data:rows.map(x=>n(x.rank)),borderColor:'#ffcf5c',backgroundColor:'rgba(255,207,92,.12)',fill:true,tension:.25,pointRadius:4}]},{plugins:{legend:{display:true}},scales:{y:{reverse:true,beginAtZero:false,ticks:{color:'#9da4bd',precision:0},grid:{color:'rgba(157,164,189,.08)'}},x:{ticks:{color:'#9da4bd'},grid:{color:'rgba(157,164,189,.08)'}}}})}
 ml.onchange=movement;if(L.length)movement();
 const hallPoints=ranked[0],hallWins=P.slice().sort((a,b)=>n(pv[b.id])-n(pv[a.id]))[0],validAvg=ranked.filter(x=>n(x.victors)>0).sort((a,b)=>n(a.average_placement,999)-n(b.average_placement,999))[0],hallLevel=levelStats[0],topLevel=scored.slice().sort((a,b)=>a.rank-b.rank)[0];
 const set=(id,text,href)=>{const e=$(id);e.textContent=text;if(href)e.href=href};if(hallPoints){set('hallPoints',hallPoints.name,`player.html?id=${hallPoints.id}`);$('hallPointsValue').textContent=n(hallPoints.total_points).toLocaleString()+' pts'}if(hallWins){set('hallWins',hallWins.name,`player.html?id=${hallWins.id}`);$('hallWinsValue').textContent=n(pv[hallWins.id])+' wins'}if(validAvg){set('hallAvg',validAvg.name,`player.html?id=${validAvg.id}`);$('hallAvgValue').textContent=n(validAvg.average_placement).toFixed(1)+' avg.'}if(hallLevel){set('hallLevel',hallLevel.name,`level.html?id=${hallLevel.id}`);$('hallLevelValue').textContent=hallLevel.victors+' victors'}if(topLevel){set('hallTopLevel',topLevel.name,`level.html?id=${topLevel.id}`);$('hallTopLevelValue').textContent=topLevel.points+' pts'}
 const climbs=L.map(l=>{const hs=H.filter(h=>h.level_id===l.id);if(hs.length<2)return null;const ranks=hs.map(h=>n(h.rank));const climb=Math.max(...ranks)-Math.min(...ranks);return {l,climb}}).filter(Boolean).sort((a,b)=>b.climb-a.climb)[0];if(climbs){set('hallClimb',climbs.l.name,`level.html?id=${climbs.l.id}`);$('hallClimbValue').textContent=climbs.climb+' rank positions'}
 const bands=[['#1–10',1,10],['#11–25',11,25],['#26–50',26,50],['#51–75',51,75],['#76–100',76,100],['#101+',101,9999]];const bandData=bands.map(b=>R.filter(r=>{const rank=n(byL[r.level_id]?.rank,0);return rank>=b[1]&&rank<=b[2]}).length);makeChart('bandChart','bar',{labels:bands.map(x=>x[0]),datasets:[{label:'Victories',data:bandData,backgroundColor:'#7c6cff'}]},{plugins:{legend:{display:false}}});
}
boot();
