const cfg=window.DIDDY_CONFIG||{};const sb=cfg.SUPABASE_URL&&cfg.SUPABASE_ANON_KEY?supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY):null;const $=id=>document.getElementById(id);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const pts=r=>Math.max(1,Math.round(100-99*Math.pow((Number(r)-1)/99,.62)));let cache=null;const DAY=864e5;
function ago(t){const n=Date.now()-new Date(t).getTime();if(n<3600000)return `${Math.max(1,Math.floor(n/60000))}m ago`;if(n<DAY)return `${Math.floor(n/3600000)}h ago`;return `${Math.floor(n/DAY)}d ago`}
function level(id){return cache.levels.find(x=>String(x.id)===String(id))}function player(id){return cache.players.find(x=>String(x.id)===String(id))}
function render(){const {levels,players,records,history,lb}=cache;const now=Date.now();const r24=records.filter(r=>now-new Date(r.created_at).getTime()>=0&&now-new Date(r.created_at).getTime()<=DAY);const r7=records.filter(r=>now-new Date(r.created_at).getTime()>=0&&now-new Date(r.created_at).getTime()<=7*DAY);const r30=records.filter(r=>now-new Date(r.created_at).getTime()>=0&&now-new Date(r.created_at).getTime()<=30*DAY);const active=new Set(r7.map(r=>r.player_id));const one=levels.filter(x=>String(x.section).toLowerCase()==='main').sort((a,b)=>Number(a.rank)-Number(b.rank))[0];const top=lb[0];
$('levelTotal').textContent=levels.length;$('playerTotal').textContent=players.length;$('wins24').textContent=r24.length.toLocaleString();$('wins7').textContent=r7.length.toLocaleString();$('active7').textContent=active.size.toLocaleString();$('top1points').textContent=one?pts(one.rank):'—';$('points7').textContent=r7.reduce((s,r)=>s+pts(level(r.level_id)?.rank||101),0).toLocaleString();
const hm={};r24.forEach(r=>hm[r.level_id]=(hm[r.level_id]||0)+1);const pm={};r7.forEach(r=>pm[r.player_id]=(pm[r.player_id]||0)+1);const movers=[];const byLevel={};history.forEach(h=>(byLevel[h.level_id]??=[]).push(h));Object.entries(byLevel).forEach(([id,rows])=>{const rr=rows.slice().sort((a,b)=>new Date(b.recorded_at)-new Date(a.recorded_at));const a=rr[0];if(!a||now-new Date(a.recorded_at).getTime()>DAY)return;const b=rr.find(x=>Number(x.rank)!==Number(a.rank)||x.section!==a.section);if(b&&Number(b.rank)!==Number(a.rank)){const l=level(id);if(l)movers.push({l,from:Number(b.rank),to:Number(a.rank),delta:Number(b.rank)-Number(a.rank),when:a.recorded_at})}});movers.sort((a,b)=>Math.abs(b.delta)-Math.abs(a.delta));$('moves24').textContent=movers.length;
$('movers').innerHTML=movers.slice(0,8).map(x=>`<a class="adminRow row between" href="level.html?id=${x.l.id}"><span><b>#${x.l.rank} · ${esc(x.l.name)}</b><span class="meta"> ${x.from>x.to?'▲':'▼'} ${Math.abs(x.delta)} spots · ${ago(x.when)}</span></span><strong>${x.from>x.to?'UP':'DOWN'}</strong></a>`).join('')||'<p class="meta">No ranked movement recorded in the last 24 hours.</p>';
$('playersPulse').innerHTML=Object.entries(pm).sort((a,b)=>b[1]-a[1]).slice(0,8).map(([id,n])=>{const p=player(id);return p?`<a class="adminRow row between" href="player.html?id=${id}"><span><b>${esc(p.name)}</b><span class="meta"> ${n} victories · last 7 days</span></span><strong>${n} wins</strong></a>`:''}).join('')||'<p class="meta">No player activity in the last 7 days.</p>';
$('levelsPulse').innerHTML=Object.entries(hm).sort((a,b)=>b[1]-a[1]).slice(0,8).map(([id,n])=>{const l=level(id);return l?`<a class="adminRow row between" href="level.html?id=${id}"><span><b>#${l.rank} · ${esc(l.name)}</b><span class="meta"> ${l.difficulty||'Level'} · 24h</span></span><strong>🔥 ${n}</strong></a>`:''}).join('')||'<p class="meta">No level has recorded a victory in the last 24 hours.</p>';
const main=levels.filter(x=>String(x.section).toLowerCase()==='main').length,ext=levels.filter(x=>String(x.section).toLowerCase()==='extended').length,legacy=levels.length-main-ext;$('structure').innerHTML=`<div><span>Main</span><b>${main}</b></div><div><span>Extended</span><b>${ext}</b></div><div><span>Legacy</span><b>${legacy}</b></div><div><span>Victories · 30d</span><b>${r30.length.toLocaleString()}</b></div><div><span>Players · 7d</span><b>${active.size}</b></div><div><span>Top player</span><b>${top?esc(top.name):'—'}</b></div>`;
const lines=[];if(one)lines.push(`👑 <b>${esc(one.name)}</b> currently occupies #1 on the list with ${pts(one.rank)} points.`);if(top)lines.push(`🏆 <b>${esc(top.name)}</b> currently leads the player leaderboard with ${Number(top.total_points||0).toLocaleString()} points.`);lines.push(`⚡ ${r24.length} victory${r24.length===1?'':'ies'} landed in the last 24 hours and ${r7.length} in the last 7 days.`);if(movers[0])lines.push(`📈 The largest recent movement is <b>${esc(movers[0].l.name)}</b>, changing ${Math.abs(movers[0].delta)} spot${Math.abs(movers[0].delta)===1?'':'s'} ${movers[0].delta>0?'up':'down'}.`);if(active.size)lines.push(`🔥 ${active.size} players have recorded at least one victory during the last 7 days.`);$('pulse').innerHTML=lines.map(x=>`<div class="briefingItem">${x}</div>`).join('');$('readout').innerHTML=`<p>The Enxy layer combines current list state, recent victories, placement history, player activity, and leaderboard data into one live readout.</p><p class="meta">This page is analytical only: it does not modify rankings, points, records, or database data.</p>`;$('pulseAge').textContent='NOW'}
async function load(){if(!sb){$('pulse').innerHTML='<div class="panel error">Configure Supabase first.</div>';return}$('refreshBtn').disabled=true;try{const q=await Promise.all([sb.from('levels').select('*').order('rank'),sb.from('players').select('*'),sb.from('records').select('*').order('created_at',{ascending:false}),sb.from('placement_history').select('*').order('recorded_at',{ascending:false}).limit(2000),sb.from('player_leaderboard').select('*').order('total_points',{ascending:false})]);const bad=q.find(x=>x.error);if(bad?.error)throw bad.error;cache={levels:q[0].data||[],players:q[1].data||[],records:q[2].data||[],history:q[3].data||[],lb:q[4].data||[]};render()}catch(e){$('pulse').innerHTML=`<div class="error">${esc(e.message||e)}<p class="meta">Enxy could not load the live data.</p></div>`}finally{$('refreshBtn').disabled=false}}
$('refreshBtn').onclick=load;load();setInterval(load,60000);